---
- hosts: raspberry_pi
  vars:
    git_user_name: "{{ lookup('env', 'GIT_USER_NAME') }}"
    git_user_email: "{{ lookup('env', 'GIT_USER_EMAIL') }}"
    nfs_server: "{{ lookup('env', 'RPI_NFS_HOMENAS_SERVER') }}"
    nfs_path: "{{ lookup('env', 'RPI_NFS_HOMENAS_PATH') }}"
    mount_point: "{{ lookup('env', 'RPI_MOUNT_POINT') }}"
    nfs_options: "defaults" # You can customize this as needed

  tasks:
    - name: Install Git
      apt:
        name: git
        state: present
      become: yes

    - name: Set Git user name
      git_config:
        scope: global
        name: user.name
        value: "{{ git_user_name }}"

    - name: Set Git user email
      git_config:
        scope: global
        name: user.email
        value: "{{ git_user_email }}"

    - name: Generate SSH key
      user:
        name: "{{ ansible_user }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: Install NFS client utilities
      apt:
        name: nfs-common
        state: present
      become: yes

    - name: Create the mount point
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'
      become: yes

    - name: Add NFS mount to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "{{ nfs_server }}:{{ nfs_path }} {{ mount_point }} nfs {{ nfs_options }} 0 0"
        state: present
      become: yes

    - name: Mount all filesystems in /etc/fstab
      command: mount -a
      become: yes
