---
- name: Update and Configure Raspberry Pis
  hosts: all
  become: true

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Update snap packages
      command: snap refresh
      ignore_errors: true

    - name: Ensure cgroup_enable line is set correctly in /boot/firmware/cmdline.txt
      lineinfile:
        path: /boot/firmware/cmdline.txt
        regexp: '^(.*)cgroup_enable(.*)$'
        line: 'cgroup_enable=memory cgroup_memory=1 net.ifnames=0 dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait'
        backrefs: yes

    - name: Reboot the Raspberry Pis
      reboot:

    - name: Wait for Raspberry Pis to be available
      wait_for_connection:
        delay: 10
        timeout: 300
