---
- name: Update Raspberry Pis
  hosts: all
  become: true

  tasks:
  - name: Update and upgrade apt packages
    apt:
      update_cache: yes
      upgrade: yes

  - name: Update snap packages
    command: snap refresh
    ignore_errors: true
